### ISSUE TITLE
Development is officially halted for a while, waiting for 1.18.

### ISSUE THREAD

**Issue by HiItsDevin** [devOS-Sanity-Edition/pastelwonderland#32]

**Comment by Stereo528** [comment]
1.18 has started

praise the crab

**Comment by HiItsDevin** [comment]
unfortunately

**Comment by Stereo528** [comment]
1.18 is also getting a version bump to 0.1.0 of the mod, instead of 0.0.3 as a lot of major changes are happening, and is basically a reimagination of the mod. however is basically backwards compt with the rest of the mod since it is all still the same blocks

oh and the fact we are moving back to java and moving the project to be developed by more people within Team Nautical, a subset of devOS: Sanity Edition that is comprised of Minecraft modders and will be specifically focusing on Minecraft modding (for the time being)
